### ISSUE TITLE
ScalaPB is unable to convert fields with multiple sections

### ISSUE THREAD

**Issue by Veske** [scalapb/sparksql-scalapb#113]
Run `sbt test` on the example https://github.com/Veske/protobuf-field-names 

This will result in an error: 
```
[info] ConvertFieldNames:
[info] - should be able to convert Scala structure to Proto *** FAILED ***
[info]   org.apache.spark.sql.AnalysisException: cannot resolve '`long_text`' given input columns: [id, text, longText];
[info]   at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
[info]   at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$$nestedInanonfun$checkAnalysis$1$2.applyOrElse(CheckAnalysis.scala:111)
[info]   at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$$nestedInanonfun$checkAnalysis$1$2.applyOrElse(CheckAnalysis.scala:108)
[info]   at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformUp$2(TreeNode.scala:280)
[info]   at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:69)
[info]   at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:280)
[info]   at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformUp$1(TreeNode.scala:277)
[info]   at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$mapChildren$1(TreeNode.scala:328)
[info]   at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:186)
[info]   at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:326)
[info]   ...
```

It is quite normal and agreed upon convention to use `camelCase` naming style for Scala code but sparksql-scalapb seems to expect the fields of the source data structure to be named in `snake_case `.

This should either be very obviously mentioned somewhere in the documentation or the default behaviour should be changed

Note: The test would not compile with `ProtoSQL.createDataFrame`.. as scalapb implicits import lacks the `GeneratedMessageCompanion`

**Comment by thesamet** [comment]
This behavior is by design. Since the common convention for Spark/SQL column names is snake_case (see [here](https://github.com/MrPowers/spark-style-guide#columns) and [here](https://docs.aws.amazon.com/athena/latest/ug/tables-databases-columns-names.html) , SparkSQL-ScalaPB expects a schema where the column names match the field names as defined in the proto (which would presumably be snake_case by convention).

I added a new option (will be available in 0.11.x) that makes it use the scala names in the schema. The syntax to use is:
```
val protoSql = new ProtoSQL(SchemaOptions().withScalaNames)
import protoSql.implicits._
protoSql.createDataFrame(...)
```

You can test it out using a snapshot, or in the mean time, renaming the case class field name to have snake_case.
